# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rl-env-server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13rl-env-server.proto\x12\x03\x65nv\"\x06\n\x04Void\"\x1f\n\x11\x43onnectionRequest\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x15NumConnectionResponse\x12\x15\n\rnumConnection\x18\x01 \x01(\x05\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\x0bInitRequest\x12\x0b\n\x03\x65nv\x18\x01 \x01(\x0c\"\x1e\n\x0cInitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"-\n\x0b\x46uncRequest\x12\x10\n\x08\x66uncName\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\x0c\",\n\x0c\x46uncResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03ret\x18\x02 \x01(\x0c\"\'\n\x0fPropertyRequest\x12\x14\n\x0cpropertyName\x18\x01 \x01(\t\"0\n\x10PropertyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03ret\x18\x02 \x01(\x0c\x32\xee\x02\n\x0bRLEnvServer\x12\x31\n\x0con_connected\x12\x16.env.ConnectionRequest\x1a\t.env.Void\x12\x34\n\x0fon_disconnected\x12\x16.env.ConnectionRequest\x1a\t.env.Void\x12\x36\n\rnumConnection\x12\t.env.Void\x1a\x1a.env.NumConnectionResponse\x12+\n\x04\x65\x63ho\x12\x10.env.EchoRequest\x1a\x11.env.EchoResponse\x12+\n\x04init\x12\x10.env.InitRequest\x1a\x11.env.InitResponse\x12+\n\x04\x66unc\x12\x10.env.FuncRequest\x1a\x11.env.FuncResponse\x12\x37\n\x08property\x12\x14.env.PropertyRequest\x1a\x15.env.PropertyResponseb\x06proto3')



_VOID = DESCRIPTOR.message_types_by_name['Void']
_CONNECTIONREQUEST = DESCRIPTOR.message_types_by_name['ConnectionRequest']
_NUMCONNECTIONRESPONSE = DESCRIPTOR.message_types_by_name['NumConnectionResponse']
_ECHOREQUEST = DESCRIPTOR.message_types_by_name['EchoRequest']
_ECHORESPONSE = DESCRIPTOR.message_types_by_name['EchoResponse']
_INITREQUEST = DESCRIPTOR.message_types_by_name['InitRequest']
_INITRESPONSE = DESCRIPTOR.message_types_by_name['InitResponse']
_FUNCREQUEST = DESCRIPTOR.message_types_by_name['FuncRequest']
_FUNCRESPONSE = DESCRIPTOR.message_types_by_name['FuncResponse']
_PROPERTYREQUEST = DESCRIPTOR.message_types_by_name['PropertyRequest']
_PROPERTYRESPONSE = DESCRIPTOR.message_types_by_name['PropertyResponse']
Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.Void)
  })
_sym_db.RegisterMessage(Void)

ConnectionRequest = _reflection.GeneratedProtocolMessageType('ConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIONREQUEST,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.ConnectionRequest)
  })
_sym_db.RegisterMessage(ConnectionRequest)

NumConnectionResponse = _reflection.GeneratedProtocolMessageType('NumConnectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _NUMCONNECTIONRESPONSE,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.NumConnectionResponse)
  })
_sym_db.RegisterMessage(NumConnectionResponse)

EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUEST,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.EchoRequest)
  })
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)

InitRequest = _reflection.GeneratedProtocolMessageType('InitRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITREQUEST,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.InitRequest)
  })
_sym_db.RegisterMessage(InitRequest)

InitResponse = _reflection.GeneratedProtocolMessageType('InitResponse', (_message.Message,), {
  'DESCRIPTOR' : _INITRESPONSE,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.InitResponse)
  })
_sym_db.RegisterMessage(InitResponse)

FuncRequest = _reflection.GeneratedProtocolMessageType('FuncRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUNCREQUEST,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.FuncRequest)
  })
_sym_db.RegisterMessage(FuncRequest)

FuncResponse = _reflection.GeneratedProtocolMessageType('FuncResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUNCRESPONSE,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.FuncResponse)
  })
_sym_db.RegisterMessage(FuncResponse)

PropertyRequest = _reflection.GeneratedProtocolMessageType('PropertyRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTYREQUEST,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.PropertyRequest)
  })
_sym_db.RegisterMessage(PropertyRequest)

PropertyResponse = _reflection.GeneratedProtocolMessageType('PropertyResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROPERTYRESPONSE,
  '__module__' : 'rl_env_server_pb2'
  # @@protoc_insertion_point(class_scope:env.PropertyResponse)
  })
_sym_db.RegisterMessage(PropertyResponse)

_RLENVSERVER = DESCRIPTOR.services_by_name['RLEnvServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=28
  _VOID._serialized_end=34
  _CONNECTIONREQUEST._serialized_start=36
  _CONNECTIONREQUEST._serialized_end=67
  _NUMCONNECTIONRESPONSE._serialized_start=69
  _NUMCONNECTIONRESPONSE._serialized_end=115
  _ECHOREQUEST._serialized_start=117
  _ECHOREQUEST._serialized_end=147
  _ECHORESPONSE._serialized_start=149
  _ECHORESPONSE._serialized_end=180
  _INITREQUEST._serialized_start=182
  _INITREQUEST._serialized_end=208
  _INITRESPONSE._serialized_start=210
  _INITRESPONSE._serialized_end=240
  _FUNCREQUEST._serialized_start=242
  _FUNCREQUEST._serialized_end=287
  _FUNCRESPONSE._serialized_start=289
  _FUNCRESPONSE._serialized_end=333
  _PROPERTYREQUEST._serialized_start=335
  _PROPERTYREQUEST._serialized_end=374
  _PROPERTYRESPONSE._serialized_start=376
  _PROPERTYRESPONSE._serialized_end=424
  _RLENVSERVER._serialized_start=427
  _RLENVSERVER._serialized_end=793
# @@protoc_insertion_point(module_scope)
